force-app/main/default/objects/HL7_Staging__c/HL7_Staging__c.object-meta.xml
<CustomObject>
    <label>HL7_Staging</label>
    <nameField>
        <displayFormat>H-{0000}</displayFormat>
        <label>HL7_Staging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HL7_Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HL7_Staging__c/fields/AccountID__c.field-meta.xml
<CustomField>
    <fullName>AccountID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>HL7_Staging</relationshipLabel>
    <relationshipName>HL7_Staging</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HL7_Staging__c/fields/HL7_Message__c.field-meta.xml
<CustomField>
    <fullName>HL7_Message__c</fullName>
    <label>HL7 Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/HL7_Staging__c/fields/IsProcessed__c.field-meta.xml
<CustomField>
    <fullName>IsProcessed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Processed?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/HL7StagingProcessingBatch.cls
public class HL7StagingProcessingBatch implements Database.Batchable<sObject>{
public Database.QueryLocator start(Database.BatchableContext context) {
      String query = 'SELECT Id, Name, IsProcessed__c,HL7_Message__c, AccountID__c FROM HL7_Staging__c WHERE IsProcessed__c = false';
        return Database.getQueryLocator(query);
    }
    public void execute(Database.BatchableContext context, List<HL7_Staging__c> scope) {
        system.debug('scope: '+scope);
        for (HL7_Staging__c record : scope) {
            record.IsProcessed__c = true;
            record.Processed_Date__c = System.now();
        }
        update scope;
    }
    public void finish(Database.BatchableContext context) {
    }   

}